name: CI Build

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            builds-args: '--bundles nsis'
            target: ''
            asset-prefix: '01'
          - platform: 'windows-11-arm'
            builds-args: '--bundles nsis'
            target: 'aarch64-pc-windows-msvc'
            asset-prefix: '01'
    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      asset-prefix: ${{ matrix.asset-prefix }}
      mobile: ${{ matrix.mobile }}
