name: 'Release: Build & Package App'

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            builds-args: '--bundles nsis'
            target: ''
            asset-prefix: '01'
          - platform: 'windows-11-arm'
            builds-args: '--bundles nsis'
            target: 'aarch64-pc-windows-msvc'
            asset-prefix: '01'
    uses: ./.github/workflows/build.yml
    with:
      release-id: ${{ github.event.release.id }}
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      asset-name-pattern: '[name]_v[version]_[platform]_[arch][ext]'
      asset-prefix: ${{ matrix.asset-prefix }}
      mobile: ${{ matrix.mobile }}
    secrets: inherit
    permissions:
      contents: write
